#!/bin/bash

#
#Copyright (c) 2016-2021, NVIDIA CORPORATION.
#SPDX-License-Identifier: Apache-2.0

set -e

wget https://www.iterm2.com/utilities/imgcat -O /usr/bin/imgcat
chmod +x /usr/bin/imgcat
exec rm -rf /usr/bin/install_imgcat
