# install python-swiftclient

#
#Copyright (c) 2016-2021, NVIDIA CORPORATION.
#SPDX-License-Identifier: Apache-2.0

---
- stat: 
    path: /home/swift/code/python-swiftclient
  register: swiftclient_stat

- name: update pip
  pip:
    name: pip
    state: present
    version: 9.0.3

- name: Install pip dependencies
  pip:
    requirements: "{{item}}"
    chdir: /home/swift/code/python-swiftclient
  with_items:
    - requirements.txt
    - test-requirements.txt
  when: swiftclient_stat.stat.exists

- name: Install swiftclient from source
  command: /usr/bin/python ./setup.py develop
  args:
    chdir: /home/swift/code/python-swiftclient
  become_user: swift
  when: swiftclient_stat.stat.exists

- name: Install swiftclient from pip
  pip:
    name: python-swiftclient
  when: not swiftclient_stat.stat.exists
