# install liberasurecode
---
- name: Is libec in components
  stat:
    path: /home/swift/code/liberasurecode
  register: libec_stat

- name: Is pyeclib in components
  stat:
    path: /home/swift/code/pyeclib
  register: pyeclib_stat

- name: Libec - install build tools (Debian)
  when: libec_stat.stat.exists and libec_stat.stat.isdir and ansible_os_family == 'Debian'
  register: build_tools_installed
  apt:
    name: ['build-essential', 'autoconf', 'automake', 'libtool']
    state: installed

- name: Libec - install build tools (RedHat)
  when: libec_stat.stat.exists and libec_stat.stat.isdir and ansible_os_family == 'RedHat'
  register: build_tools_installed
  yum:
    name: ['gcc', 'make', 'autoconf', 'automake', 'libtool']
    state: installed

- name: Libec - install from source
  when: libec_stat.stat.exists and libec_stat.stat.isdir and build_tools_installed is success
  register: libec_installed
  shell: ./autogen.sh && ./configure && make && sudo make install && sed -i '1s/^/\/usr\/local\/lib\n/' /etc/ld.so.conf && ldconfig
  args:
    chdir: /home/swift/code/liberasurecode

- name: pyeclib - install from source
  when: pyeclib_stat.stat.exists and libec_installed is success
  register: pyeclib_installed
  shell: pip install -e . && pip install -r test-requirements.txt
  args:
    chdir: /home/swift/code/pyeclib
