# install swift
---
- name: install sudo
  yum:
    name: ['sudo']
    state: installed
  when: ansible_os_family == 'RedHat'

- name: Create etc swift
  file:
    path: /etc/swift
    state: directory
    mode: 0755
    owner: swift
    group: swift
  register: etcswiftcreated

- name: Create swift config files
  register: swiftconfigscreated
  when: etcswiftcreated is success and not tiny_install
  copy:
    src: /home/swift/code/swift/doc/saio/swift/
    dest: /etc/swift/
    owner: swift
    group: swift

# We get proxy-server.conf from the Swift repo (doc/saio/swift/proxy-server.conf),
# so any modifications need to be done after getting the file.

- name: yum install patch
  yum:
    name: ['patch']
    state: present
  become: yes
  become_user: root
  when: ansible_os_family == 'RedHat'

- name: apt install patch
  apt:
    name: ['patch']
    state: present
  become: yes
  become_user: root
  when: ansible_os_family == 'Debian'

- name: apply patch to file
  patch:
    src: "patches/proxy-server.conf.patch"
    dest: "/etc/swift/proxy-server.conf"

# End of patching /etc/swift/proxy-server.conf

- name: Copy custom swift.conf file for ProxyFS
  when: etcswiftcreated is success and proxyfs
  copy:
    src: proxyfs/etc/swift/
    dest: /etc/swift/
    owner: swift
    group: swift

- name: Create tiny swift config files
  register: swiftconfigscreated
  when: etcswiftcreated is success and tiny_install
  copy:
    src: single_replica_policy/etc/swift/
    dest: /etc/swift/
    owner: swift
    group: swift

- name: Create swift test config file
  when: etcswiftcreated is success and not tiny_install
  copy:
    src: /home/swift/code/swift/test/sample.conf
    dest: /etc/swift/test.conf
    owner: swift
    group: swift

- name: list of the .conf files and store it in register
  raw: find /etc/swift -type f -name "*.conf"
  register: swift_conf_files
  when: swiftconfigscreated is success and not tiny_install

- name: Set swift user in configs
  register: configsed
  when: swift_conf_files is success and not tiny_install
  with_items: "{{ swift_conf_files.stdout_lines }}"
  replace:
    dest: "{{ item }}"
    regexp: user = <your-user-name>
    replace: user = swift

- name: Move SAIO bin scripts
  register: bin_scripts
  when: etcswiftcreated is success
  copy:
    src: /home/swift/code/swift/doc/saio/bin/
    dest: /home/swift/bin
    owner: swift
    group: swift
    mode: 0775

- name: Copy modified remakerings
  when: not tiny_install and not proxyfs
  copy:
    src: remakerings
    dest: /home/swift/bin/remakerings
    owner: swift
    group: swift
    mode: 0775

- name: Copy modified remakerings for tiny
  when: tiny_install
  copy:
    src: single_replica_policy/remakerings
    dest: /home/swift/bin/remakerings
    owner: swift
    group: swift
    mode: 0775

- name: Copy modified remakerings for ProxyFS
  when: proxyfs
  copy:
    src: proxyfs/remakerings
    dest: /home/swift/bin/remakerings
    owner: swift
    group: swift
    mode: 0775

- name: Add bin to PATH
  copy:
    src: path_home_bin.sh
    dest: /etc/profile.d
    owner: root
    group: root

- name: Set up rsync on boot (Debian)
  register: rsyncsetup
  replace:
    dest: /etc/default/rsync
    regexp: RSYNC_ENABLE=false
    replace: RSYNC_ENABLE=true
  when: ansible_os_family == 'Debian' and not tiny_install

- name: Create /etc/default/rsyncd file (RedHat)
  copy:
    src: etc/default/rsyncd
    dest: /etc/default/rsyncd
    force: no
  when: ansible_os_family == 'RedHat' and not tiny_install

- name: Set up rsync on boot (RedHat)
  register: rsyncsetup
  replace:
    dest: /etc/default/rsyncd
    regexp: RSYNC_ENABLE=false
    replace: RSYNC_ENABLE=true
  when: ansible_os_family == 'RedHat' and not tiny_install

- name: rsync config file
  when: not tiny_install
  copy:
    src: /home/swift/code/swift/doc/saio/rsyncd.conf
    dest: /etc/rsyncd.conf

- name: set swift user in rsync config
  when: not tiny_install
  replace:
    dest: /etc/rsyncd.conf
    regexp: user = <your-user-name>
    replace: user = swift

- name: start rsync (Debian)
  service:
    name: rsync
    state: restarted
  when: ansible_os_family == 'Debian' and not tiny_install

- name: start rsyncd (RedHat)
  systemd:
    name: rsyncd
    state: restarted
    daemon_reload: yes
    enabled: yes
  when: ansible_os_family == 'RedHat' and not tiny_install

- import_tasks: setup_swift_logging.yaml

- import_tasks: install_libec.yaml

- name: install dependencies
  register: swiftdependenciesinstalled
  apt:
    name: ['curl', 'gcc', 'memcached', 'sqlite3']
    state: installed
  when: ansible_os_family == 'Debian'

- name: install dependencies
  register: swiftdependenciesinstalled
  yum:
    name: ['curl', 'gcc', 'memcached', 'sqlite']
    state: installed
  when: ansible_os_family == 'RedHat'

- name: update pip
  pip:
    name: pip
    state: present
    version: 9.0.3

- name: update setuptools
  pip:
    name: setuptools
    state: latest

- name: install pip dependencies
  pip:
    requirements: "{{item}}"
    chdir: /home/swift/code/swift
  with_items:
    - requirements.txt
    - test-requirements.txt

- name: Install swift
  register: swiftinstalled
  when: swiftdependenciesinstalled is success and libec_installed is success
  command: /usr/bin/python ./setup.py develop
  args:
    chdir: /home/swift/code/swift
  become_user: swift

- name: Build rings
  when: swiftinstalled is success
  register: ringssetup
  command: ./remakerings
  args:
    chdir: /home/swift/bin/

- name: Set /etc/swift permissions
  file:
    group: swift
    owner: swift
    path: /etc/swift/
    recurse: yes
    state: directory

- name: Start Swift
  when: tiny_install
  command: ./swift-init main start && ./swift-init container-updater start
  args:
    chdir: /home/swift/code/swift/bin
