# install swift
---
- name: Create etc swift
  when: swiftusercreated|success
  file:
    path: /etc/swift
    state: directory
    mode: 0755
    owner: swift
    group: swift
  register: etcswiftcreated

- name: Create swift config files
  register: swiftconfigscreated
  when: etcswiftcreated|success
  copy:
    src: /home/swift/runway_components/swift/doc/saio/swift/
    dest: /etc/swift/
    owner: swift
    group: swift

- name: list of the .conf files and store it in register
  raw: find /etc/swift -type f -name "*.conf"
  register: swift_conf_files
  when: swiftconfigscreated|success

- name: Set swift user in configs
  register: configsed
  when: swift_conf_files|success
  with_items: swift_conf_files.stdout_lines
  replace:
    dest: "{{ item }}"
    regexp: user = <your-user-name>
    replace: user = swift

- name: Set up rsync
  register: rsyncsetup
  replace:
    dest: /etc/default/rsync
    regexp: RSYNC_ENABLE=false
    replace: RSYNC_ENABLE=true

- name: install dependencies
  register: swiftdependenciesinstalled
  apt: name={{item}} state=installed
  with_items:
    - curl
    - gcc
    - memcached
    # - rsync
    - sqlite3
    # - xfsprogs
    # - git-core
    - libffi-dev
    - python-setuptools
    - liberasurecode-dev
    - libssl-dev
    - python-coverage
    - python-dev
    - python-nose
    - python-xattr
    - python-eventlet
    - python-greenlet
    - python-pastedeploy
    - python-netifaces
    - python-pip
    - python-dnspython
    - python-mock

- name: Install swift
  register: swiftinstalled
  when: swiftdependenciesinstalled|success
  command: /usr/bin/python ./setup.py develop
  args:
    chdir: /home/swift/runway_components/swift
  become_user: swift

- name: Build rings
  when: swiftinstalled|success
  register: ringssetup
  command: ./make_rings.sh
  args:
    chdir: /root/ansible

- name: Start swift
  register: swiftstarted
  when: ringssetup|success
  command: swift-init main start
  become_user: swift
