# configure syslog and systemd
---
- name: copy swift log file
  copy:
    src: /home/swift/code/swift/doc/saio/rsyslog.d/10-swift.conf
    dest: /etc/rsyslog.d/10-swift.conf

- name: update syslog group
  replace:
    dest: /etc/rsyslog.conf
    regexp: $PrivDropToGroup syslog
    replace: $PrivDropToGroup adm

- name: make swift log folders
  file:
    path: /var/log/swift/hourly
    state: directory
    mode: 0775
    owner: syslog
    group: adm
    recurse: yes
  when: ansible_os_family == 'Debian'

- name: make combined logs
  replace:
    dest: /etc/rsyslog.d/10-swift.conf
    regexp: '#local1,local2,local3,local4,local5.*   /var/log/swift/all.log'
    replace: 'local0,local1,local2,local3,local4,local5.*   /var/log/swift/all.log'

- name: make hourly logs, part 1
  replace:
    dest: /etc/rsyslog.d/10-swift.conf
    regexp: '#$template HourlyProxyLog,"/var/log/swift/hourly/%$YEAR%%$MONTH%%$DAY%%$HOUR%"'
    replace: '$template HourlyProxyLog,"/var/log/swift/hourly/%$YEAR%%$MONTH%%$DAY%%$HOUR%"'

- name: make hourly logs, part 2
  replace:
    dest: /etc/rsyslog.d/10-swift.conf
    regexp: '#local1.*;local1.!notice ?HourlyProxyLog'
    replace: 'local1.*;local1.!notice ?HourlyProxyLog'

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: config systemd log rate limiting
  replace:
    dest: /etc/systemd/journald.conf
    regexp: '#RateLimitInterval=30s'
    replace: 'RateLimitInterval=0s'
    regexp: '#RateLimitBurst=1000'
    replace: 'RateLimitBurst=0'

- name: reload systemd config daemon-reload
  command: systemctl daemon-reload

