---

- name: Create swift group
  group:
    name: swift
    state: present
  register: swiftgroupcreated


- name: Create swift user
  when: swiftgroupcreated|success
  user:
    name: swift
    group: swift
    # password is "password"
    password: $6$EgUVKk/vDpZbfJ$gtzFx.iN.iVbglXGBWaOeptejT3phyjmQWW.YeX5F75EMuNzqvOh1icDOHUlYapBiXna4pVNK5Zg6ZYPraXRm/
  register: swiftusercreated


- name: Create etc swift
  when: swiftusercreated|success
  file:
    path: /etc/swift
    state: directory
    mode: 0755
    owner: swift
    group: swift
  register: etcswiftcreated


- name: Create swift config files
  register: swiftconfigscreated
  when: etcswiftcreated|success
  copy:
    src: ../swift/doc/saio/swift/
    dest: /etc/swift/
    owner: swift
    group: swift

- name: list of the .conf files and store it in register
  raw: find /etc/swift -type f -name "*.conf"
  register: swift_conf_files
  when: swiftconfigscreated|success

- name: Set swift user in configs
  register: configsed
  when: swift_conf_files|success
  with_items: swift_conf_files.stdout_lines
  replace:
    dest: "{{ item }}"
    regexp: user = <your-user-name>
    replace: user = swift


- name: Make filesystems on disks
  register: filesystemscreated
  with_items:
    - sdb
    - sdc
    - sdd
    - sde
    - sdf
    - sdg
    - sdh
    - sdi
  filesystem:
    fstype: xfs
    dev: /dev/{{ item }}
    force: no

- name: Mount disks
  register: drivesmounted
  when: filesystemscreated|success
  with_items:
    - { drive: sdb, mp: /srv/1/node/d1 }
    - { drive: sdc, mp: /srv/2/node/d2 }
    - { drive: sdd, mp: /srv/3/node/d3 }
    - { drive: sde, mp: /srv/4/node/d4 }
    - { drive: sdf, mp: /srv/1/node/d5 }
    - { drive: sdg, mp: /srv/2/node/d6 }
    - { drive: sdh, mp: /srv/3/node/d7 }
    - { drive: sdi, mp: /srv/4/node/d8 }
  mount:
    name: "{{ item.mp }}"
    src: /dev/{{ item.drive }}
    fstype: xfs
    state: mounted
    opts: noatime,nodiratime,logbufs=2

- name: Set permissions
  register: permissionsset
  when: drivesmounted|success
  with_items:
    - /srv/1
    - /srv/2
    - /srv/3
    - /srv/4
  file:
    recurse: yes
    owner: swift
    group: swift
    path: "{{ item }}"


- name: Set up rsync
  register: rsyncsetup
  replace:
    dest: /etc/default/rsync
    regexp: RSYNC_ENABLE=false
    replace: RSYNC_ENABLE=true

- name: install dependencies
  register: swiftdependenciesinstalled
  apt: name={{item}} state=installed
  with_items:
    - curl
    - gcc
    - memcached
    # - rsync
    - sqlite3
    # - xfsprogs
    # - git-core
    - libffi-dev
    - python-setuptools
    - liberasurecode-dev
    - libssl-dev
    - python-coverage
    - python-dev
    - python-nose
    - python-xattr
    - python-eventlet
    - python-greenlet
    - python-pastedeploy
    - python-netifaces
    - python-pip
    - python-dnspython
    - python-mock

- name: Install swift
  register: swiftinstalled
  when: swiftdependenciesinstalled|success
  command: /usr/bin/python ./setup.py develop
  args:
    chdir: /root/swift


- name: Build rings
  when: swiftinstalled|success
  register: ringssetup
  command: ./make_rings.sh
  args:
    chdir: /root/ansible


- name: Start swift
  register: swiftstarted
  when: ringssetup|success
  command: swift-init main start
