# starting point for ansible deploy

#
#Copyright (c) 2016-2021, NVIDIA CORPORATION.
#SPDX-License-Identifier: Apache-2.0

---
- name: Most of the shebang
  hosts: localhost
  vars:
    tiny_install: "{{ tiny_install|bool }}"
  roles:
    - swift
    - python-swiftclient
