# starting point for ansible deploy
---
- name: The whole shebang
  hosts: localhost
  vars:
    jsonVar: "{{ lookup('file', '/tmp/drives.json') | from_json }}"
  tasks:
    - include: tasks/main.yaml
