#!/bin/bash

#
#Copyright (c) 2016-2021, NVIDIA CORPORATION.
#SPDX-License-Identifier: Apache-2.0

set -e

cd /etc/swift

rm -f *.builder *.ring.gz backups/*.builder backups/*.ring.gz

swift-ring-builder object.builder create 10 3 1
swift-ring-builder object.builder add r1z1-127.0.0.1:6210/d1 1
swift-ring-builder object.builder add r1z2-127.0.0.2:6220/d2 1
swift-ring-builder object.builder add r1z3-127.0.0.3:6230/d3 1
swift-ring-builder object.builder add r1z4-127.0.0.4:6240/d4 1
swift-ring-builder object.builder rebalance
swift-ring-builder object-1.builder create 10 2 1
swift-ring-builder object-1.builder add r1z1-127.0.0.1:6210/d1 1
swift-ring-builder object-1.builder add r1z2-127.0.0.2:6220/d2 1
swift-ring-builder object-1.builder add r1z3-127.0.0.3:6230/d3 1
swift-ring-builder object-1.builder add r1z4-127.0.0.4:6240/d4 1
swift-ring-builder object-1.builder rebalance
swift-ring-builder object-2.builder create 10 6 1
swift-ring-builder object-2.builder add r1z1-127.0.0.1:6210/d1 1
swift-ring-builder object-2.builder add r1z1-127.0.0.1:6210/d5 1
swift-ring-builder object-2.builder add r1z2-127.0.0.2:6220/d2 1
swift-ring-builder object-2.builder add r1z2-127.0.0.2:6220/d6 1
swift-ring-builder object-2.builder add r1z3-127.0.0.3:6230/d3 1
swift-ring-builder object-2.builder add r1z3-127.0.0.3:6230/d7 1
swift-ring-builder object-2.builder add r1z4-127.0.0.4:6240/d4 1
swift-ring-builder object-2.builder add r1z4-127.0.0.4:6240/d8 1
swift-ring-builder object-2.builder rebalance
swift-ring-builder container.builder create 10 3 1
swift-ring-builder container.builder add r1z1-127.0.0.1:6211/d1 1
swift-ring-builder container.builder add r1z2-127.0.0.2:6221/d2 1
swift-ring-builder container.builder add r1z3-127.0.0.3:6231/d3 1
swift-ring-builder container.builder add r1z4-127.0.0.4:6241/d4 1
swift-ring-builder container.builder rebalance
swift-ring-builder account.builder create 10 3 1
swift-ring-builder account.builder add r1z1-127.0.0.1:6212/d1 1
swift-ring-builder account.builder add r1z2-127.0.0.2:6222/d2 1
swift-ring-builder account.builder add r1z3-127.0.0.3:6232/d3 1
swift-ring-builder account.builder add r1z4-127.0.0.4:6242/d4 1
swift-ring-builder account.builder rebalance
